-- Seed Data: 40 Exact Wildlife Classes (Index 0 - 39)
-- Matches model data.yaml and classification system exactly

INSERT OR IGNORE INTO animals (class_index, animal_name, scientific_name, description) VALUES
(0, 'Lion', 'Panthera leo', 'Apex carnivore native to sub-Saharan Africa and the Gir Forest of India, living in social prides.'),
(1, 'Tiger', 'Panthera tigris', 'Largest living cat species, recognized by its reddish-orange coat with dark vertical stripes.'),
(2, 'African Elephant', 'Loxodonta africana', 'Largest terrestrial mammal, possessing large ears to radiate heat and a dexterous trunk.'),
(3, 'Leopard', 'Panthera pardus', 'Solitary and opportunistic spotted big cat known for extraordinary arboreal agility.'),
(4, 'Cheetah', 'Acinonyx jubatus', 'Fastest land animal capable of reaching sprint speeds exceeding 100 km/h with non-retractable claws.'),
(5, 'Rhinoceros', 'Rhinocerotidae', 'Large herbivorous odd-toed ungulate characterized by thick protective skin and keratinous nasal horns.'),
(6, 'Hippopotamus', 'Hippopotamus amphibius', 'Large, mostly herbivorous, semiaquatic mammal native to sub-Saharan rivers and lakes.'),
(7, 'Giraffe', 'Giraffa camelopardalis', 'Tallest living terrestrial animal characterized by its long neck and distinctive coat blotches.'),
(8, 'Zebra', 'Equus quagga', 'African equines renowned for their high-contrast black-and-white striped coats.'),
(9, 'Gorilla', 'Gorilla beringei', 'Ground-dwelling, predominantly herbivorous great apes inhabiting equatorial African forests.'),
(10, 'Brown Bear', 'Ursus arctos', 'Large bear species distributed across Eurasia and North America, including grizzly bears.'),
(11, 'Polar Bear', 'Ursus maritimus', 'Hypercarnivorous Arctic bear largely adapted for ice marine environments and sea ice hunting.'),
(12, 'Gray Wolf', 'Canis lupus', 'Largest wild member of the family Canidae, exhibiting complex pack structure and territorial behavior.'),
(13, 'Red Fox', 'Vulpes vulpes', 'Highly adaptable omnivorous canid with a rusty-red coat, white chest, and bushy black-tipped tail.'),
(14, 'Jaguar', 'Panthera onca', 'Largest feline species in the Americas, with a rosette-patterned coat and exceptionally powerful bite.'),
(15, 'Snow Leopard', 'Panthera uncia', 'Elusive solitary feline adapted to the high, rugged mountain ranges of Central and South Asia.'),
(16, 'Giant Panda', 'Ailuropoda melanoleuca', 'Specialized folivorous bear endemic to south-central China, feeding almost exclusively on bamboo.'),
(17, 'Orangutan', 'Pongo pygmaeus', 'Arboreal great ape native to the rainforests of Borneo and Sumatra with distinctive reddish-orange hair.'),
(18, 'Kangaroo', 'Macropodidae', 'Marsupial endemic to Australia known for its powerful hind legs, large feet, and muscular tail.'),
(19, 'Koala', 'Phascolarctos cinereus', 'Arboreal herbivorous marsupial native to eastern Australia that feeds primarily on eucalyptus foliage.'),
(20, 'Moose', 'Alces alces', 'Largest extant species in the deer family, characterized by broad, palmate antlers in adult males.'),
(21, 'American Bison', 'Bison bison', 'North American megafauna characterized by a massive hump, woolly coat, and short curved horns.'),
(22, 'Reindeer', 'Rangifer tarandus', 'Arctic and subarctic deer known as caribou in North America, where both males and females grow antlers.'),
(23, 'Sea Otter', 'Enhydra lutris', 'Marine mammal native to the coasts of the northern Pacific Ocean, relying on dense fur for insulation.'),
(24, 'Sloth', 'Folivora', 'Arboreal neotropical xenarthrans known for their slow movement and upside-down suspension in tree canopies.'),
(25, 'Wild Boar', 'Sus scrofa', 'Suid native to much of Eurasia and North Africa, with prominent canine tusks and coarse bristly hair.'),
(26, 'Nile Crocodile', 'Crocodylus niloticus', 'Large apex aquatic predator widespread across sub-Saharan African freshwater biomes.'),
(27, 'American Alligator', 'Alligator mississippiensis', 'Semiaquatic crocodilian endemic to the southeastern United States with a broad, rounded snout.'),
(28, 'Komodo Dragon', 'Varanus komodoensis', 'Largest living lizard species, endemic to the Indonesian islands of Komodo, Rinca, and Flores.'),
(29, 'King Cobra', 'Ophiophagus hannah', 'World''s longest venomous snake, native to forests from India through Southeast Asia.'),
(30, 'Bald Eagle', 'Haliaeetus leucocephalus', 'Sea eagle native to North America with a distinctive white head, dark brown body, and yellow hooked bill.'),
(31, 'Golden Eagle', 'Aquila chrysaetos', 'One of the best-known birds of prey in the Northern Hemisphere, with golden plumage on the back of its neck.'),
(32, 'Great Horned Owl', 'Bubo virginianus', 'Adaptable nocturnal raptor with distinctive ear tufts, mottled camouflage, and deep hooting calls.'),
(33, 'Flamingo', 'Phoenicopteridae', 'Wading bird renowned for its vivid pink and reddish plumage derived from dietary carotenoid pigments.'),
(34, 'Emperor Penguin', 'Aptenodytes forsteri', 'Tallest and heaviest of all living penguin species, endemic to the frigid Antarctic coastlines.'),
(35, 'Macaw', 'Ara macao', 'Large, colorful New World parrot with a long tail and formidable curved beak adapted for cracking seeds.'),
(36, 'Great White Shark', 'Carcharodon carcharias', 'Apex marine predatory fish known for its large size, conical snout, and serrated teeth.'),
(37, 'Blue Whale', 'Balaenoptera musculus', 'Marine mammal and the largest animal known to have ever existed on Earth.'),
(38, 'Bottlenose Dolphin', 'Tursiops truncatus', 'Highly intelligent marine cetacean known for its curved mouth giving a perpetual smile appearance.'),
(39, 'Giant Pacific Octopus', 'Enteroctopus dofleini', 'Largest octopus species, inhabiting the temperate coastal waters of the North Pacific.');
